=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ActivitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActivitiesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ActivitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivitiesApi' do
    it 'should create an instance of ActivitiesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ActivitiesApi)
    end
  end

  # unit tests for cancel_server_activities
  # Cancel Server Activities
  # Cancel Server Activities
  # @param activity_uuid The UUID of the activity to cancel.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_server_activities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_server_activities
  # Get Server Activities
  # Get Server Activities
  # @param [Hash] opts the optional parameters
  # @return [GetServerActivities200Response]
  describe 'get_server_activities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
