=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for library_sections_section_id_tag_get
  # Retrieve Information by Section and Tag
  # Fetches details from a specific section of the library identified by a section key and a tag. The tag parameter accepts the following values: - &#x60;all&#x60;: All items in the section. - &#x60;unwatched&#x60;: Items that have not been played. - &#x60;newest&#x60;: Items that are recently released. - &#x60;recentlyAdded&#x60;: Items that are recently added to the library. - &#x60;recentlyViewed&#x60;: Items that were recently viewed. - &#x60;onDeck&#x60;: Items to continue watching. - &#x60;collection&#x60;: Items categorized by collection. - &#x60;edition&#x60;: Items categorized by edition. - &#x60;genre&#x60;: Items categorized by genre. - &#x60;year&#x60;: Items categorized by year of release. - &#x60;decade&#x60;: Items categorized by decade. - &#x60;director&#x60;: Items categorized by director. - &#x60;actor&#x60;: Items categorized by starring actor. - &#x60;country&#x60;: Items categorized by country of origin. - &#x60;contentRating&#x60;: Items categorized by content rating. - &#x60;rating&#x60;: Items categorized by rating. - &#x60;resolution&#x60;: Items categorized by resolution. - &#x60;firstCharacter&#x60;: Items categorized by the first letter. - &#x60;folder&#x60;: Items categorized by folder. - &#x60;search?type&#x3D;1&#x60;: Search functionality within the section. 
  # @param section_id the Id of the library to query
  # @param tag A key representing a specific tag within the section.
  # @param [Hash] opts the optional parameters
  # @return [LibrarySectionsSectionIdTagGet200Response]
  describe 'library_sections_section_id_tag_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
