=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HubsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HubsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::HubsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HubsApi' do
    it 'should create an instance of HubsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::HubsApi)
    end
  end

  # unit tests for get_global_hubs
  # Get Global Hubs
  # Get Global Hubs filtered by the parameters provided.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count The number of items to return with each hub.
  # @option opts [Integer] :only_transient Only return hubs which are \&quot;transient\&quot;, meaning those which are prone to changing after media playback or addition (e.g. On Deck, or Recently Added).
  # @return [nil]
  describe 'get_global_hubs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_library_hubs
  # Get library specific hubs
  # This endpoint will return a list of library specific hubs 
  # @param section_id the Id of the library to query
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count The number of items to return with each hub.
  # @option opts [Integer] :only_transient Only return hubs which are \&quot;transient\&quot;, meaning those which are prone to changing after media playback or addition (e.g. On Deck, or Recently Added).
  # @return [nil]
  describe 'get_library_hubs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
