=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SecurityApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecurityApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SecurityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurityApi' do
    it 'should create an instance of SecurityApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SecurityApi)
    end
  end

  # unit tests for get_source_connection_information
  # Get Source Connection Information
  # If a caller requires connection details and a transient token for a source that is known to the server, for example a cloud media provider or shared PMS, then this endpoint can be called. This endpoint is only accessible with either an admin token or a valid transient token generated from an admin token. Note: requires Plex Media Server &gt;&#x3D; 1.15.4. 
  # @param source The source identifier with an included prefix.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_source_connection_information test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_transient_token
  # Get a Transient Token.
  # This endpoint provides the caller with a temporary token with the same access level as the caller&#39;s token. These tokens are valid for up to 48 hours and are destroyed if the server instance is restarted. 
  # @param type &#x60;delegation&#x60; - This is the only supported &#x60;type&#x60; parameter.
  # @param scope &#x60;all&#x60; - This is the only supported &#x60;scope&#x60; parameter.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_transient_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
