=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SessionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SessionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionsApi' do
    it 'should create an instance of SessionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SessionsApi)
    end
  end

  # unit tests for get_session_history
  # Get Session History
  # This will Retrieve a listing of all history views.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_session_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sessions
  # Get Active Sessions
  # This will retrieve the \&quot;Now Playing\&quot; Information of the PMS.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_transcode_sessions
  # Get Transcode Sessions
  # Get Transcode Sessions
  # @param [Hash] opts the optional parameters
  # @return [GetTranscodeSessions200Response]
  describe 'get_transcode_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stop_transcode_session
  # Stop a Transcode Session
  # Stop a Transcode Session
  # @param session_key the Key of the transcode session to stop
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'stop_transcode_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
