=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UpdaterApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UpdaterApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UpdaterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdaterApi' do
    it 'should create an instance of UpdaterApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UpdaterApi)
    end
  end

  # unit tests for apply_updates
  # Apply Updates
  # Note that these two parameters are effectively mutually exclusive. The &#x60;tonight&#x60; parameter takes precedence and &#x60;skip&#x60; will be ignored if &#x60;tonight&#x60; is also passed 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :tonight Indicate that you want the update to run during the next Butler execution. Omitting this or setting it to false indicates that the update should install
  # @option opts [Integer] :skip Indicate that the latest version should be marked as skipped. The &lt;Release&gt; entry for this version will have the &#x60;state&#x60; set to &#x60;skipped&#x60;.
  # @return [nil]
  describe 'apply_updates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_for_updates
  # Checking for updates
  # Checking for updates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :download Indicate that you want to start download any updates found.
  # @return [nil]
  describe 'check_for_updates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_update_status
  # Querying status of updates
  # Querying status of updates
  # @param [Hash] opts the optional parameters
  # @return [GetUpdateStatus200Response]
  describe 'get_update_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
