=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::VideoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VideoApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::VideoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideoApi' do
    it 'should create an instance of VideoApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::VideoApi)
    end
  end

  # unit tests for get_timeline
  # Get the timeline for a media item
  # Get the timeline for a media item
  # @param rating_key The rating key of the media item
  # @param key The key of the media item to get the timeline for
  # @param state The state of the media item
  # @param has_mde Whether the media item has MDE
  # @param time The time of the media item
  # @param duration The duration of the media item
  # @param context The context of the media item
  # @param play_queue_item_id The play queue item ID of the media item
  # @param play_back_time The playback time of the media item
  # @param row The row of the media item
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_timeline test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for start_universal_transcode
  # Start Universal Transcode
  # Begin a Universal Transcode Session
  # @param has_mde Whether the media item has MDE
  # @param path The path to the media item to transcode
  # @param media_index The index of the media item to transcode
  # @param part_index The index of the part to transcode
  # @param protocol The protocol to use for the transcode session
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :fast_seek Whether to use fast seek or not
  # @option opts [Float] :direct_play Whether to use direct play or not
  # @option opts [Float] :direct_stream Whether to use direct stream or not
  # @option opts [Float] :subtitle_size The size of the subtitles
  # @option opts [String] :subtites The subtitles
  # @option opts [Float] :audio_boost The audio boost
  # @option opts [String] :location The location of the transcode session
  # @option opts [Float] :media_buffer_size The size of the media buffer
  # @option opts [String] :session The session ID
  # @option opts [Float] :add_debug_overlay Whether to add a debug overlay or not
  # @option opts [Float] :auto_adjust_quality Whether to auto adjust quality or not
  # @return [nil]
  describe 'start_universal_transcode test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
