=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  class GetOnDeck200ResponseMediaContainerMetadataInner
    attr_accessor :allow_sync

    attr_accessor :library_section_id

    attr_accessor :library_section_title

    attr_accessor :library_section_uuid

    attr_accessor :rating_key

    attr_accessor :key

    attr_accessor :parent_rating_key

    attr_accessor :grandparent_rating_key

    attr_accessor :guid

    attr_accessor :parent_guid

    attr_accessor :grandparent_guid

    attr_accessor :type

    attr_accessor :title

    attr_accessor :grandparent_key

    attr_accessor :parent_key

    attr_accessor :library_section_key

    attr_accessor :grandparent_title

    attr_accessor :parent_title

    attr_accessor :content_rating

    attr_accessor :summary

    attr_accessor :index

    attr_accessor :parent_index

    attr_accessor :last_viewed_at

    attr_accessor :year

    attr_accessor :thumb

    attr_accessor :art

    attr_accessor :parent_thumb

    attr_accessor :grandparent_thumb

    attr_accessor :grandparent_art

    attr_accessor :grandparent_theme

    attr_accessor :duration

    attr_accessor :originally_available_at

    attr_accessor :added_at

    attr_accessor :updated_at

    attr_accessor :media

    attr_accessor :guid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'allow_sync' => :'allowSync',
        :'library_section_id' => :'librarySectionID',
        :'library_section_title' => :'librarySectionTitle',
        :'library_section_uuid' => :'librarySectionUUID',
        :'rating_key' => :'ratingKey',
        :'key' => :'key',
        :'parent_rating_key' => :'parentRatingKey',
        :'grandparent_rating_key' => :'grandparentRatingKey',
        :'guid' => :'guid',
        :'parent_guid' => :'parentGuid',
        :'grandparent_guid' => :'grandparentGuid',
        :'type' => :'type',
        :'title' => :'title',
        :'grandparent_key' => :'grandparentKey',
        :'parent_key' => :'parentKey',
        :'library_section_key' => :'librarySectionKey',
        :'grandparent_title' => :'grandparentTitle',
        :'parent_title' => :'parentTitle',
        :'content_rating' => :'contentRating',
        :'summary' => :'summary',
        :'index' => :'index',
        :'parent_index' => :'parentIndex',
        :'last_viewed_at' => :'lastViewedAt',
        :'year' => :'year',
        :'thumb' => :'thumb',
        :'art' => :'art',
        :'parent_thumb' => :'parentThumb',
        :'grandparent_thumb' => :'grandparentThumb',
        :'grandparent_art' => :'grandparentArt',
        :'grandparent_theme' => :'grandparentTheme',
        :'duration' => :'duration',
        :'originally_available_at' => :'originallyAvailableAt',
        :'added_at' => :'addedAt',
        :'updated_at' => :'updatedAt',
        :'media' => :'Media',
        :'guid' => :'Guid'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'allow_sync' => :'Boolean',
        :'library_section_id' => :'Float',
        :'library_section_title' => :'String',
        :'library_section_uuid' => :'String',
        :'rating_key' => :'Float',
        :'key' => :'String',
        :'parent_rating_key' => :'Float',
        :'grandparent_rating_key' => :'Float',
        :'guid' => :'String',
        :'parent_guid' => :'String',
        :'grandparent_guid' => :'String',
        :'type' => :'String',
        :'title' => :'String',
        :'grandparent_key' => :'String',
        :'parent_key' => :'String',
        :'library_section_key' => :'String',
        :'grandparent_title' => :'String',
        :'parent_title' => :'String',
        :'content_rating' => :'String',
        :'summary' => :'String',
        :'index' => :'Float',
        :'parent_index' => :'Float',
        :'last_viewed_at' => :'Float',
        :'year' => :'Float',
        :'thumb' => :'String',
        :'art' => :'String',
        :'parent_thumb' => :'String',
        :'grandparent_thumb' => :'String',
        :'grandparent_art' => :'String',
        :'grandparent_theme' => :'String',
        :'duration' => :'Float',
        :'originally_available_at' => :'Time',
        :'added_at' => :'Float',
        :'updated_at' => :'Float',
        :'media' => :'Array<GetOnDeck200ResponseMediaContainerMetadataInnerMediaInner>',
        :'guid' => :'Array<GetOnDeck200ResponseMediaContainerMetadataInnerGuidInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::GetOnDeck200ResponseMediaContainerMetadataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::GetOnDeck200ResponseMediaContainerMetadataInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'allow_sync')
        self.allow_sync = attributes[:'allow_sync']
      end

      if attributes.key?(:'library_section_id')
        self.library_section_id = attributes[:'library_section_id']
      end

      if attributes.key?(:'library_section_title')
        self.library_section_title = attributes[:'library_section_title']
      end

      if attributes.key?(:'library_section_uuid')
        self.library_section_uuid = attributes[:'library_section_uuid']
      end

      if attributes.key?(:'rating_key')
        self.rating_key = attributes[:'rating_key']
      end

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      end

      if attributes.key?(:'parent_rating_key')
        self.parent_rating_key = attributes[:'parent_rating_key']
      end

      if attributes.key?(:'grandparent_rating_key')
        self.grandparent_rating_key = attributes[:'grandparent_rating_key']
      end

      if attributes.key?(:'guid')
        self.guid = attributes[:'guid']
      end

      if attributes.key?(:'parent_guid')
        self.parent_guid = attributes[:'parent_guid']
      end

      if attributes.key?(:'grandparent_guid')
        self.grandparent_guid = attributes[:'grandparent_guid']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'grandparent_key')
        self.grandparent_key = attributes[:'grandparent_key']
      end

      if attributes.key?(:'parent_key')
        self.parent_key = attributes[:'parent_key']
      end

      if attributes.key?(:'library_section_key')
        self.library_section_key = attributes[:'library_section_key']
      end

      if attributes.key?(:'grandparent_title')
        self.grandparent_title = attributes[:'grandparent_title']
      end

      if attributes.key?(:'parent_title')
        self.parent_title = attributes[:'parent_title']
      end

      if attributes.key?(:'content_rating')
        self.content_rating = attributes[:'content_rating']
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      end

      if attributes.key?(:'index')
        self.index = attributes[:'index']
      end

      if attributes.key?(:'parent_index')
        self.parent_index = attributes[:'parent_index']
      end

      if attributes.key?(:'last_viewed_at')
        self.last_viewed_at = attributes[:'last_viewed_at']
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      end

      if attributes.key?(:'thumb')
        self.thumb = attributes[:'thumb']
      end

      if attributes.key?(:'art')
        self.art = attributes[:'art']
      end

      if attributes.key?(:'parent_thumb')
        self.parent_thumb = attributes[:'parent_thumb']
      end

      if attributes.key?(:'grandparent_thumb')
        self.grandparent_thumb = attributes[:'grandparent_thumb']
      end

      if attributes.key?(:'grandparent_art')
        self.grandparent_art = attributes[:'grandparent_art']
      end

      if attributes.key?(:'grandparent_theme')
        self.grandparent_theme = attributes[:'grandparent_theme']
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      end

      if attributes.key?(:'originally_available_at')
        self.originally_available_at = attributes[:'originally_available_at']
      end

      if attributes.key?(:'added_at')
        self.added_at = attributes[:'added_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'media')
        if (value = attributes[:'media']).is_a?(Array)
          self.media = value
        end
      end

      if attributes.key?(:'guid')
        if (value = attributes[:'guid']).is_a?(Array)
          self.guid = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          allow_sync == o.allow_sync &&
          library_section_id == o.library_section_id &&
          library_section_title == o.library_section_title &&
          library_section_uuid == o.library_section_uuid &&
          rating_key == o.rating_key &&
          key == o.key &&
          parent_rating_key == o.parent_rating_key &&
          grandparent_rating_key == o.grandparent_rating_key &&
          guid == o.guid &&
          parent_guid == o.parent_guid &&
          grandparent_guid == o.grandparent_guid &&
          type == o.type &&
          title == o.title &&
          grandparent_key == o.grandparent_key &&
          parent_key == o.parent_key &&
          library_section_key == o.library_section_key &&
          grandparent_title == o.grandparent_title &&
          parent_title == o.parent_title &&
          content_rating == o.content_rating &&
          summary == o.summary &&
          index == o.index &&
          parent_index == o.parent_index &&
          last_viewed_at == o.last_viewed_at &&
          year == o.year &&
          thumb == o.thumb &&
          art == o.art &&
          parent_thumb == o.parent_thumb &&
          grandparent_thumb == o.grandparent_thumb &&
          grandparent_art == o.grandparent_art &&
          grandparent_theme == o.grandparent_theme &&
          duration == o.duration &&
          originally_available_at == o.originally_available_at &&
          added_at == o.added_at &&
          updated_at == o.updated_at &&
          media == o.media &&
          guid == o.guid
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [allow_sync, library_section_id, library_section_title, library_section_uuid, rating_key, key, parent_rating_key, grandparent_rating_key, guid, parent_guid, grandparent_guid, type, title, grandparent_key, parent_key, library_section_key, grandparent_title, parent_title, content_rating, summary, index, parent_index, last_viewed_at, year, thumb, art, parent_thumb, grandparent_thumb, grandparent_art, grandparent_theme, duration, originally_available_at, added_at, updated_at, media, guid].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
