=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  class GetMyPlexAccount200ResponseMyPlex
    attr_accessor :auth_token

    attr_accessor :username

    attr_accessor :mapping_state

    attr_accessor :mapping_error

    attr_accessor :sign_in_state

    attr_accessor :public_address

    attr_accessor :public_port

    attr_accessor :private_address

    attr_accessor :private_port

    attr_accessor :subscription_features

    attr_accessor :subscription_active

    attr_accessor :subscription_state

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auth_token' => :'authToken',
        :'username' => :'username',
        :'mapping_state' => :'mappingState',
        :'mapping_error' => :'mappingError',
        :'sign_in_state' => :'signInState',
        :'public_address' => :'publicAddress',
        :'public_port' => :'publicPort',
        :'private_address' => :'privateAddress',
        :'private_port' => :'privatePort',
        :'subscription_features' => :'subscriptionFeatures',
        :'subscription_active' => :'subscriptionActive',
        :'subscription_state' => :'subscriptionState'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auth_token' => :'String',
        :'username' => :'String',
        :'mapping_state' => :'String',
        :'mapping_error' => :'String',
        :'sign_in_state' => :'String',
        :'public_address' => :'String',
        :'public_port' => :'Float',
        :'private_address' => :'String',
        :'private_port' => :'Float',
        :'subscription_features' => :'String',
        :'subscription_active' => :'Boolean',
        :'subscription_state' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::GetMyPlexAccount200ResponseMyPlex` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::GetMyPlexAccount200ResponseMyPlex`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auth_token')
        self.auth_token = attributes[:'auth_token']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'mapping_state')
        self.mapping_state = attributes[:'mapping_state']
      end

      if attributes.key?(:'mapping_error')
        self.mapping_error = attributes[:'mapping_error']
      end

      if attributes.key?(:'sign_in_state')
        self.sign_in_state = attributes[:'sign_in_state']
      end

      if attributes.key?(:'public_address')
        self.public_address = attributes[:'public_address']
      end

      if attributes.key?(:'public_port')
        self.public_port = attributes[:'public_port']
      end

      if attributes.key?(:'private_address')
        self.private_address = attributes[:'private_address']
      end

      if attributes.key?(:'private_port')
        self.private_port = attributes[:'private_port']
      end

      if attributes.key?(:'subscription_features')
        self.subscription_features = attributes[:'subscription_features']
      end

      if attributes.key?(:'subscription_active')
        self.subscription_active = attributes[:'subscription_active']
      end

      if attributes.key?(:'subscription_state')
        self.subscription_state = attributes[:'subscription_state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auth_token == o.auth_token &&
          username == o.username &&
          mapping_state == o.mapping_state &&
          mapping_error == o.mapping_error &&
          sign_in_state == o.sign_in_state &&
          public_address == o.public_address &&
          public_port == o.public_port &&
          private_address == o.private_address &&
          private_port == o.private_port &&
          subscription_features == o.subscription_features &&
          subscription_active == o.subscription_active &&
          subscription_state == o.subscription_state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auth_token, username, mapping_state, mapping_error, sign_in_state, public_address, public_port, private_address, private_port, subscription_features, subscription_active, subscription_state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
