=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  class GetLibraryItems200ResponseMediaContainer
    attr_accessor :size

    attr_accessor :allow_sync

    attr_accessor :art

    attr_accessor :identifier

    attr_accessor :library_section_id

    attr_accessor :library_section_title

    attr_accessor :library_section_uuid

    attr_accessor :media_tag_prefix

    attr_accessor :media_tag_version

    attr_accessor :thumb

    attr_accessor :title1

    attr_accessor :title2

    attr_accessor :view_group

    attr_accessor :view_mode

    attr_accessor :metadata

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'size' => :'size',
        :'allow_sync' => :'allowSync',
        :'art' => :'art',
        :'identifier' => :'identifier',
        :'library_section_id' => :'librarySectionID',
        :'library_section_title' => :'librarySectionTitle',
        :'library_section_uuid' => :'librarySectionUUID',
        :'media_tag_prefix' => :'mediaTagPrefix',
        :'media_tag_version' => :'mediaTagVersion',
        :'thumb' => :'thumb',
        :'title1' => :'title1',
        :'title2' => :'title2',
        :'view_group' => :'viewGroup',
        :'view_mode' => :'viewMode',
        :'metadata' => :'Metadata'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'size' => :'Integer',
        :'allow_sync' => :'Boolean',
        :'art' => :'String',
        :'identifier' => :'String',
        :'library_section_id' => :'Integer',
        :'library_section_title' => :'String',
        :'library_section_uuid' => :'String',
        :'media_tag_prefix' => :'String',
        :'media_tag_version' => :'Integer',
        :'thumb' => :'String',
        :'title1' => :'String',
        :'title2' => :'String',
        :'view_group' => :'String',
        :'view_mode' => :'Integer',
        :'metadata' => :'Array<GetLibraryItems200ResponseMediaContainerMetadataInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::GetLibraryItems200ResponseMediaContainer` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::GetLibraryItems200ResponseMediaContainer`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'allow_sync')
        self.allow_sync = attributes[:'allow_sync']
      end

      if attributes.key?(:'art')
        self.art = attributes[:'art']
      end

      if attributes.key?(:'identifier')
        self.identifier = attributes[:'identifier']
      end

      if attributes.key?(:'library_section_id')
        self.library_section_id = attributes[:'library_section_id']
      end

      if attributes.key?(:'library_section_title')
        self.library_section_title = attributes[:'library_section_title']
      end

      if attributes.key?(:'library_section_uuid')
        self.library_section_uuid = attributes[:'library_section_uuid']
      end

      if attributes.key?(:'media_tag_prefix')
        self.media_tag_prefix = attributes[:'media_tag_prefix']
      end

      if attributes.key?(:'media_tag_version')
        self.media_tag_version = attributes[:'media_tag_version']
      end

      if attributes.key?(:'thumb')
        self.thumb = attributes[:'thumb']
      end

      if attributes.key?(:'title1')
        self.title1 = attributes[:'title1']
      end

      if attributes.key?(:'title2')
        self.title2 = attributes[:'title2']
      end

      if attributes.key?(:'view_group')
        self.view_group = attributes[:'view_group']
      end

      if attributes.key?(:'view_mode')
        self.view_mode = attributes[:'view_mode']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Array)
          self.metadata = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          size == o.size &&
          allow_sync == o.allow_sync &&
          art == o.art &&
          identifier == o.identifier &&
          library_section_id == o.library_section_id &&
          library_section_title == o.library_section_title &&
          library_section_uuid == o.library_section_uuid &&
          media_tag_prefix == o.media_tag_prefix &&
          media_tag_version == o.media_tag_version &&
          thumb == o.thumb &&
          title1 == o.title1 &&
          title2 == o.title2 &&
          view_group == o.view_group &&
          view_mode == o.view_mode &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [size, allow_sync, art, identifier, library_section_id, library_section_title, library_section_uuid, media_tag_prefix, media_tag_version, thumb, title1, title2, view_group, view_mode, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
