=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetSessions200ResponseMediaContainerMetadataInnerUser
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetSessions200ResponseMediaContainerMetadataInnerUser do
  let(:instance) { OpenapiClient::GetSessions200ResponseMediaContainerMetadataInnerUser.new }

  describe 'test an instance of GetSessions200ResponseMediaContainerMetadataInnerUser' do
    it 'should create an instance of GetSessions200ResponseMediaContainerMetadataInnerUser' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::GetSessions200ResponseMediaContainerMetadataInnerUser)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "thumb"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
