=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetLibrary200ResponseMediaContainerTypeInnerFilterInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetLibrary200ResponseMediaContainerTypeInnerFilterInner do
  let(:instance) { OpenapiClient::GetLibrary200ResponseMediaContainerTypeInnerFilterInner.new }

  describe 'test an instance of GetLibrary200ResponseMediaContainerTypeInnerFilterInner' do
    it 'should create an instance of GetLibrary200ResponseMediaContainerTypeInnerFilterInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::GetLibrary200ResponseMediaContainerTypeInnerFilterInner)
    end
  end

  describe 'test attribute "filter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filter_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
