=begin
#Plex-API

#An Open API Spec for interacting with Plex.tv and Plex Servers

The version of the OpenAPI document: 0.0.3
Contact: Lukeslakemail@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetServerActivities200ResponseMediaContainerActivityInnerContext
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetServerActivities200ResponseMediaContainerActivityInnerContext do
  let(:instance) { OpenapiClient::GetServerActivities200ResponseMediaContainerActivityInnerContext.new }

  describe 'test an instance of GetServerActivities200ResponseMediaContainerActivityInnerContext' do
    it 'should create an instance of GetServerActivities200ResponseMediaContainerActivityInnerContext' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::GetServerActivities200ResponseMediaContainerActivityInnerContext)
    end
  end

  describe 'test attribute "library_section_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
